name: APIM Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Synapse
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Synapse with Maven
      run: mvn clean install --file pom.xml
    - name: Get synapse version
      run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout > ../SYNAPSE_VERSION_FILE
    - name: Print synapse version
      run: |
        echo $(cat ../SYNAPSE_VERSION_FILE)
    - name: Checkout APIM
      uses: actions/checkout@v1
      with: 
        repository: wso2/product-apim
        ref: refs/heads/master
    - name: Build APIM with Maven
      run: mvn clean install -Dsynapse.version=$(cat ../SYNAPSE_VERSION_FILE) -DskipTests -fae --file ../product-apim/pom.xml
